grid_settings:
  gridsize: 0.25 #0.25 #pixel resolution size
  limit: [-89.875, 89.875, -179.875, 179.875] # [-90., 90., -180., 180.] #rectangle to grid (default is full world)
  fill_value: 9999. #default is NAN
  time_interval: 30 #minute intervals that will be split
  time_start: "2020/01/01/00/00" # year/month/day/hour/min
  time_end: "2020/01/01/00/29"   # year/month/day/hour/min

variables:
  geo_var: ["latitude", "longitude"] #default (what geophysical variables are mapped to)
  phy_var: ["Sensor_Zenith", "Scattering_Angle", "Image_Optical_Depth_Land_And_Ocean", "Optical_Depth_Land_And_Ocean"] # output names and master list
  phy_var_nc: ["sensor_zenith_angle", "Scattering_Angle", "Image_Optical_Depth_Land_And_Ocean", "Optical_Depth_Land_And_Ocean"] # geophysical variables netCDF
  phy_var_hdf: ["Sensor_Zenith", "Scattering_Angle", "Image_Optical_Depth_Land_And_Ocean","Optical_Depth_Land_And_Ocean"] # geophysical variables hdf
  aod_range: [-0.05, 5.] # aod range only 
  
file_io:
  # file_location_folder takes precedence over file_location_file unless "NA"
  #file_location_folder: "/mnt/c/Users/bobgr/Desktop/Spring 2022 NASA/Gridtools Package (Code, README, inputs, outputs, examples, verification)/SampleInputs limited/"
  file_location_folder: "/mnt/c/Users/bobgr/Desktop/Spring 2022 NASA/Gridtools Package (Code, README, inputs, outputs, examples, verification)/SampleInputs 0000-0059 01-01-2020/"
  file_location_file: "PATH/file_name_containing_paths_of_specific_files_to_read.txt"
  output_location: "/mnt/c/Users/bobgr/Desktop/Spring 2022 NASA/Gridtools Package (Code, README, inputs, outputs, examples, verification)/SampleOutputs 0000-0059 01-01-2020/"
  output_name: "OUTPUTv15" # output files will contain this name+time_interval
  static_file: "/mnt/c/Users/bobgr/Desktop/Spring 2022 NASA/Gridtools Package (Code, README, inputs, outputs, examples, verification)/LSM_ELV_QDEG_FIXED.nc"
