grid_settings:
  gridsize: 0.25 #0.25 #pixel resolution size
  limit: [-89.875, 89.875, -179.875, 179.875] # [-90., 90., -180., 180.] #rectangle to grid (default is full world)
  fill_value: -9999. #default is NAN
  time_interval: 30 #minute intervals that will be split
  time_start: "2020/01/01/00/00" # year/month/day/hour/min
  time_end: "2020/01/01/00/29"   # year/month/day/hour/min

variables:
  geo_var: ["latitude", "longitude"] #default (what geophysical variables are mapped to)
  phy_var: ["Sensor_Zenith", "Scattering_Angle", "Image_Optical_Depth_Land_And_Ocean", "Optical_Depth_Land_And_Ocean"] # output names and master list
  phy_var_nc: ["sensor_zenith_angle", "Scattering_Angle", "Image_Optical_Depth_Land_And_Ocean", "Optical_Depth_Land_And_Ocean"] # geophysical variables netCDF
  phy_var_hdf: ["Sensor_Zenith", "Scattering_Angle", "Image_Optical_Depth_Land_And_Ocean","Optical_Depth_Land_And_Ocean"] # geophysical variables hdf
  aod_range: [-0.05, 5.] # aod range only (metadata is different, metadata takes precedence) 
  pixel_range: [0, 500] # Range for pixel count at single pixel

file_io:
  # file_directory_folder takes precedence over fole_location_folder unless "NA"
  # file_location_folder takes precedence over file_location_file unless "NA"
  # file_directory_folder will read subdirectories
  # file_location_folder will not
  file_directory_folder: "/app/src/inputs/"
  file_location_folder: "PATH/to/single/directory/"
  file_location_file: "PATH/file_name_containing_paths_of_specific_files_to_read.txt"
  output_location: "/app/src/outputs/"
  output_name: "OUTPUTv15" # output files will contain this name+time_interval
  static_file: "/app/src/static/LSM_ELV_QDEG_FIXED.nc"
